#!/usr/bin/env python3
"""backup_memory.py — backup/DR for the memory pillar (~/.memory).

Why: the Wiki + SQLite databases are the kit's cross-chat memory — the one
asset that cannot be rebuilt from the repo (db/*.db are gitignored by
design; everything else in ~/.memory is rebuildable via install.py).
SQLite warns against raw file copies of live databases (WAL corruption,
https://www.sqlite.org/howtocorrupt.html §2.2) — so .db files go through
sqlite3's online backup API, everything else through copytree.

Usage:
    python scripts/tools/backup_memory.py                     # backup
    python scripts/tools/backup_memory.py --restore-drill DIR  # restore+verify drill
    python scripts/tools/backup_memory.py --restore DIR [--yes]  # LIVE restore
    python scripts/tools/backup_memory.py --full               # old whole-root scope
    python scripts/tools/backup_memory.py --list
"""
import argparse
import json
import os
import re
import shutil
import sqlite3
import sys
import tempfile
import time
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:  # noqa: S110,BLE001 — optional console nicety
    pass

DEFAULT_ROOT = Path.home() / ".memory"
# Files that are rebuilt by install.py / build.py — excluded from backups.
REBUILDABLE = {"_compat.pyc", "__pycache__"}
SQLITE_SIDECAR_SUFFIXES = ("-wal", "-shm", "-journal")
DEFAULT_KEEP = 10


def _prune_completed(dest: Path, keep: int, marker: str = ".complete") -> None:
    completed = sorted(
        p for p in dest.iterdir()
        if p.is_dir() and (p / marker).is_file()
    ) if dest.is_dir() else []
    for old in completed[:-max(1, keep)]:
        shutil.rmtree(old)


def _is_corruption(e: sqlite3.Error) -> bool:
    """Damage vs mere busyness: 'database is locked' is an
    OperationalError, hence a DatabaseError subclass — treating a BUSY
    db as corrupt would unlink a healthy live store (advisory
    2026-09-03). Only header/page damage counts."""
    msg = str(e).lower()
    return ("malformed" in msg or "not a database" in msg
            or "disk image" in msg)


def memory_root() -> Path:
    import os
    return Path(os.environ.get("MEMORY_ROOT") or DEFAULT_ROOT)


def _backup_db(src: Path, dst: Path, busy_timeout: float = 5.0) -> None:
    """One database via sqlite3 online backup API (WAL-safe), STEPPED
    and PRE-PROBED: the backup API does NOT honor busy timeouts —
    sqlite3_backup_step returns SQLITE_BUSY immediately and CPython's
    Connection.backup() retries it in an unbounded sleep loop, so a
    merely BUSY source would spin forever (advisory 2026-09-03). A
    STATEMENT does honor timeout=: probe the source first so a held
    lock surfaces as OperationalError('database is locked') and the
    caller tags it LOCKED instead of hanging (the tiny probe→backup
    race is acceptable; the retry path is idempotent)."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    src_con = sqlite3.connect(str(src), timeout=busy_timeout)
    dst_con = sqlite3.connect(str(dst), timeout=busy_timeout)
    try:
        src_con.execute("SELECT COUNT(*) FROM sqlite_master").fetchone()
        while src_con.backup(dst_con, pages=500):
            pass
        dst_con.commit()
    finally:
        src_con.close()
        dst_con.close()


def backup(dest: Path | None = None, root: Path | None = None,
           keep: int = DEFAULT_KEEP, full: bool = False,
           suffix: str = "") -> dict:
    """Create a timestamped backup, then retain newest `keep`.

    Default scope is the CORE memory: db/research.db + Wiki/ — the only
    state that is not rebuildable from the repo (code indexes like
    agent.db are regenerated by build.py; backing them up cost ~21 MB
    per stamp of non-data, plan Q1). --full restores the old walk.
    `suffix` names safety snapshots (pre-restore)."""

    root = root or memory_root()
    if not root.is_dir():
        raise FileNotFoundError(f"memory root missing: {root}")
    stamp = time.strftime("%Y%m%dT%H%M%S")
    target = (dest or root / "backups") / (stamp + suffix)
    if target.exists():  # same-second rerun
        target = target.with_name(target.name + "_1")
    target.mkdir(parents=True)

    copied, dbs = 0, 0
    skipped: list = []
    if full:
        items = sorted(root.rglob("*"))
    else:
        items = []
        wiki = root / "Wiki"
        if wiki.is_dir():
            items += sorted(wiki.rglob("*"))
        rdb = root / "db" / "research.db"
        if rdb.is_file():
            items.append(rdb)
    for item in items:
        rel = item.relative_to(root)
        # Never back up the backups, caches, or rebuildable engine state.
        if "backups" in rel.parts or any(p in REBUILDABLE for p in rel.parts):
            continue
        if item.name.endswith(SQLITE_SIDECAR_SUFFIXES):
            continue
        if item.is_dir():
            (target / rel).mkdir(parents=True, exist_ok=True)
            continue
        out = target / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        if item.suffix in (".db", ".sqlite", ".sqlite3", ".db3"):
            try:
                _backup_db(item, out)
            except sqlite3.Error as e:
                # unreadable live db (the DR case): the pre-restore
                # snapshot must not die on it; restore replaces it.
                # A BUSY db (locked) is NOT unreadable — skipping it
                # silently would ship a backup without the store, so
                # surface it loudly in the result.
                out.unlink(missing_ok=True)
                skipped.append(
                    f"{rel}: {'CORRUPT' if _is_corruption(e) else 'LOCKED'}: {e}")
                continue
            dbs += 1
        else:
            shutil.copy2(item, out)
            copied += 1
    if skipped:
        # DEGRADED snapshot: no .complete, so it never graduates into
        # a restore point (--list, _prune_completed and the offsite
        # copy all key off .complete); the marker records why. A
        # hollow dir handed to --restore would "succeed" over an
        # untouched live db (advisory 2026-09-03).
        (target / ".degraded").write_text("\n".join(skipped) + "\n",
                                          encoding="utf-8")
        offsite = None
    else:
        (target / ".complete").write_text("ok\n", encoding="utf-8")
        offsite = _offsite_copy(target, keep)
    _prune_completed(target.parent, keep)
    _prune_completed(target.parent, 3, ".degraded")  # DR evidence, small cap
    return {"name": target.name, "path": str(target),
            "files": copied, "dbs": dbs, "skipped": skipped,
            "scope": "full" if full else "core",
            "offsite": offsite}



def _offsite_copy(target: Path, keep: int) -> str | None:
    """Second copy OUTSIDE the backups folder (plan P6, no cloud by
    constraint): MEMORY_ROOT_BACKUP_DEST names a dir on another
    volume/share. Absent env -> None, primary-only backup."""
    dest = os.environ.get("MEMORY_ROOT_BACKUP_DEST")
    if not dest:
        return None
    off = Path(dest) / target.name
    if off.exists():
        shutil.rmtree(off)
    shutil.copytree(target, off)
    _prune_completed(Path(dest), keep)
    return str(off)


def restore(backup_dir: Path, root: Path | None = None,
            include_degraded: bool = False) -> dict:
    """Restore Wiki + research.db from BACKUP_DIR into the LIVE root.

    Order is the safety contract: (1) fresh core snapshot of the live
    root into backups/<stamp>-pre-restore/ BEFORE touching anything —
    if the live db is DAMAGED (the DR case) the snapshot degrades to a
    `pre_restore_skipped` record instead of aborting (nothing is
    destroyed yet), but a snapshot failure on a merely BUSY db aborts
    the restore: proceeding without a safety copy is how a lock turns
    into total loss; (2) replace — backups never carry -wal/-shm
    sidecars, so the stale live sidecars are deleted once the
    new file is in place, with no live connection open: a stale WAL
    beside the replaced file is free for SQLite to replay; (3) verify
    the live store with the drill's findings probe (P5 heals a pre-FTS
    index on first connect). A
    corrupt live db is unlinked with its sidecars; a merely BUSY one
    aborts the restore with the live file intact (locked != damaged)."""
    root = root or memory_root()
    backup_dir = Path(backup_dir)
    if not backup_dir.is_dir():
        raise FileNotFoundError(f"backup dir missing: {backup_dir}")
    if (backup_dir / ".degraded").is_file() and not include_degraded:
        why = (backup_dir / ".degraded").read_text(
            encoding="utf-8", errors="replace").strip()
        raise RuntimeError(
            f"backup {backup_dir.name} is DEGRADED (skipped at backup "
            f"time: {why}) — restoring it would report success without "
            f"restoring the store; pass include_degraded/--include-"
            f"degraded only if that is intended")
    pre = backup(dest=root / "backups", root=root,
                 suffix="-pre-restore")
    locked = [s for s in pre["skipped"] if ": LOCKED:" in s]
    if locked:
        # a safety snapshot WITHOUT the store is no safety copy: a
        # lock-then-replace sequence is silent total loss (advisory
        # 2026-09-03). Nothing was destroyed yet — drop the hollow
        # snapshot and refuse.
        shutil.rmtree(pre["path"], ignore_errors=True)
        raise RuntimeError(
            f"pre-restore snapshot could not read a live (locked?) db: "
            f"{'; '.join(locked)} — refusing to restore without a "
            f"safety copy")
    pre_restore = pre["name"]
    pre_skipped = "; ".join(pre["skipped"]) or None
    done = []
    bwiki = backup_dir / "Wiki"
    if bwiki.is_dir():
        live = root / "Wiki"
        if live.is_dir():
            shutil.rmtree(live)
        shutil.copytree(bwiki, live)
        done.append("Wiki")
    brdb = backup_dir / "db" / "research.db"
    if brdb.is_file():
        (root / "db").mkdir(parents=True, exist_ok=True)
        live_db = root / "db" / "research.db"
        try:
            _backup_db(brdb, live_db)
        except sqlite3.DatabaseError as e:
            if not _is_corruption(e):
                raise  # busy, not damaged: abort, keep live db AND wal
            for side in (live_db, *[Path(str(live_db) + s) for s in
                                   SQLITE_SIDECAR_SUFFIXES]):
                side.unlink(missing_ok=True)
            _backup_db(brdb, live_db)
        # backups never carry sidecars; the replaced file must not sit
        # beside the OLD -wal (SQLite would replay it). Deleted only
        # after the new file is in place — before it, a busy-path abort
        # would drop committed-but-uncheckpointed rows.
        for side in (Path(str(live_db) + s)
                     for s in SQLITE_SIDECAR_SUFFIXES):
            side.unlink(missing_ok=True)
        done.append("db/research.db")
    else:
        # explicit override path (--include-degraded): say loudly that
        # the store is NOT part of this restore
        print(f"[!] backup carries no db/research.db — the live store "
              f"is NOT restored by this run", file=sys.stderr)
    verify = _findings_probe(root)
    return {"pre_restore": pre_restore, "pre_restore_skipped": pre_skipped,
            "restored": done, "verify": verify}

def _findings_probe(restored: Path) -> dict:
    """Findings half of the restore drill (advisory 2026-09-02): search_all
    cannot see research.db (no files_fts), and PRAGMA integrity_check is
    blind to FTS desync — so probe the findings store directly.

    Three layers, in order:
    1. raw FTS5 integrity-check rank=1 on a TEMP copy (content comparison
       needs rank=1, SQLite docs §6.7; it is a write-tx INSERT so never on
       the restored file itself, and connect()'s backfill would heal an
       empty index before we could see it). Detects a backup that ARRIVED
       desynced: empty index -> 'database disk image is malformed', stale
       content -> 'checksum mismatch'.
    2. findings.py doctor (rc + output) — heals and certifies the store.
    3. functional MATCH of a token DERIVED from the restored db itself
       (real backups carry real findings, never test literals): first
       unicode61 token of the newest long text. No findings / no FTS /
       no derivable token -> search skipped, counts+doctor only.
    """
    import os
    import subprocess

    out: dict = {"present": False, "ok": False, "counts": None,
                 "raw_rank1": None, "doctor_rc": None, "cli": None,
                 "search_token": None, "search_rc": None,
                 "search_hits": None}
    db = restored / "db" / "research.db"
    if not db.is_file():
        out["ok"] = True  # memory roots without findings are legitimate
        return out
    out["present"] = True

    tmp = Path(tempfile.mkdtemp(prefix="drill-findings-"))
    try:
        copy = tmp / "research.db"
        try:
            _backup_db(db, copy)
        except sqlite3.Error as e:
            # unreadable db (corrupt backup): integrity_ok already covers
            # page-level damage, but the findings probe must not crash
            out["raw_rank1"] = f"unreadable: {e}"
            out["ok"] = False
            return out
        con = sqlite3.connect(str(copy))
        try:
            n_tab = con.execute(
                "SELECT COUNT(*) FROM findings").fetchone()[0]
            has_fts = con.execute(
                "SELECT COUNT(*) FROM sqlite_master WHERE name = "
                "'findings_fts'").fetchone()[0]
            n_fts = (con.execute(
                "SELECT COUNT(*) FROM findings_fts_docsize").fetchone()[0]
                if has_fts else None)
            out["counts"] = {"table": n_tab, "indexed": n_fts}
            if has_fts:
                try:
                    con.execute("INSERT INTO findings_fts(findings_fts, "
                                "rank) VALUES('integrity-check', 1)")
                    out["raw_rank1"] = "passed"
                except sqlite3.DatabaseError as e:
                    out["raw_rank1"] = f"failed: {e}"
            else:
                out["raw_rank1"] = "no fts"
        finally:
            con.close()

        # MEMORY_ROOT must NOT leak into the probe subprocess: drill runs
        # inside a seeded/odd root (tests) whose markers _compat rejects
        # at import; the db under test is pinned via MEMORY_ROOT_RESEARCH_DB.
        env = {k: v for k, v in os.environ.items() if k != "MEMORY_ROOT"}
        env.update(MEMORY_ROOT_RESEARCH_DB=str(copy),
                   PYTHONIOENCODING="utf-8")
        # CLI resolution: repo kit first, then the deployed/live root,
        # then the roots themselves — a deployed copy of THIS file has no
        # repo at parents[2]; record which path ran (None = skipped).
        here = Path(__file__).resolve()
        cli = next((c / "findings.py" for c in (
            here.parents[2] / "memory" / "db-tools",
            here.parents[1] / "db-tools",
            memory_root() / "db-tools",
            restored / "db-tools") if (c / "findings.py").is_file()), None)
        out["cli"] = str(cli) if cli else None
        findings_cli = cli
        if findings_cli is not None:
            r = subprocess.run(
                [sys.executable, str(findings_cli), "doctor"],
                capture_output=True, text=True, encoding="utf-8",
                errors="replace", timeout=120, check=False, env=env)
            out["doctor_rc"] = r.returncode
            out["doctor_out"] = (r.stdout or r.stderr).strip()[:200]

            # token derived from the restored content, never a fixture
            con = sqlite3.connect(str(copy))
            text = ""
            try:
                row = con.execute(
                    "SELECT text FROM findings WHERE length(text) > 12 "
                    "ORDER BY id DESC LIMIT 1").fetchone()
                text = row[0] if row else ""
            except sqlite3.Error:
                text = ""
            finally:
                con.close()
            m = re.search(r"[^\W_\d]{3,}", text or "")
            if m:
                token = m.group(0)
                out["search_token"] = token
                r2 = subprocess.run(
                    [sys.executable, str(findings_cli), "search", token,
                     "--json"],
                    capture_output=True, text=True, encoding="utf-8",
                    errors="replace", timeout=120, check=False, env=env)
                out["search_rc"] = r2.returncode
                if r2.returncode != 0:
                    out["search_err"] = (r2.stderr or r2.stdout).strip()[:200]
                try:
                    out["search_hits"] = len(json.loads(r2.stdout or "[]"))
                except json.JSONDecodeError:
                    out["search_hits"] = None
        # skipped layers (cli absent) must not read as failed ones
        out["ok"] = out["raw_rank1"] in ("passed", "no fts")
        if out["doctor_rc"] is not None:
            out["ok"] = (out["ok"] and out["doctor_rc"] == 0
                         and (out["search_hits"] is None
                              or (out["search_rc"] == 0
                                  and out["search_hits"] >= 1)))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    return out



def restore_drill(backup_dir: Path, root: Path | None = None) -> dict:
    """Restore a backup into a temp MEMORY_ROOT and VERIFY it inside that
    root's lifetime (the temp dir is deleted before returning — callers
    get facts, never a live path).

    Verification: every restored .db passes `PRAGMA integrity_check`; the
    findings store gets a dedicated probe (`_findings_probe`: raw FTS5
    rank=1 content check on a temp copy, findings.py doctor, functional
    search of a token derived from the restored rows) because search_all
    cannot see research.db; and (when the memory root carries db-tools)
    search_all.py runs against the restored copy. Returns {"files",
    "dbs", "integrity_ok", "findings", "probe"}."""
    import os
    import subprocess

    root = root or memory_root()
    if not backup_dir.is_dir():
        raise FileNotFoundError(f"backup dir missing: {backup_dir}")

    result: dict = {"files": 0, "dbs": 0, "integrity_ok": False,
                    "findings": None, "probe": None}
    if (backup_dir / ".degraded").is_file():
        # a snapshot that skipped a db is not a restore point: the
        # findings probe would certify whatever the LIVE root happens
        # to hold, i.e. green over nothing restored (advisory 2026-09-03)
        result["degraded"] = (backup_dir / ".degraded").read_text(
            encoding="utf-8", errors="replace").strip()
        return result
    with tempfile.TemporaryDirectory(prefix="memory-drill-") as tmp:
        restored = Path(tmp) / "memory"
        shutil.copytree(backup_dir, restored)
        result["files"] = sum(1 for p in restored.rglob("*") if p.is_file())
        db_files = sorted(restored.rglob("*.db"))
        result["dbs"] = len(db_files)

        # integrity_check on every restored database
        ok = True
        for db in db_files:
            con = None
            try:
                con = sqlite3.connect(str(db))
                row = con.execute("PRAGMA integrity_check").fetchone()
                if not row or row[0] != "ok":
                    ok = False
                    break
            except sqlite3.DatabaseError:
                ok = False
                break
            finally:
                if con is not None:
                    con.close()
        result["integrity_ok"] = ok

        # findings half: search_all is blind to research.db (no files_fts)
        result["findings"] = _findings_probe(restored)


        # search probe against the restored root — only when the restored
        # tree IS a memory root: search_all.py validates MEMORY_ROOT at
        # import (chulan_root markers), and a CORE backup (research.db +
        # Wiki only) restores without them; running it there dies with a
        # RuntimeError traceback on a perfectly good restore. The
        # findings half above covers research.db either way.
        markers = ("VERSION", "db-tools", "scripts/_compat.py")
        has_markers = all((restored / m).exists() for m in markers)
        tool = root / "db-tools" / "search_all.py"
        probe: dict = {"tool": str(tool), "exists": tool.is_file(),
                       "skipped": not has_markers}
        if tool.is_file() and has_markers:
            r = subprocess.run(
                [sys.executable, str(tool), "test"],
                capture_output=True, text=True, encoding="utf-8",
                errors="replace", timeout=120, check=False,
                env={**os.environ, "MEMORY_ROOT": str(restored)})
            probe["returncode"] = r.returncode
            probe["first_lines"] = (r.stdout or r.stderr).strip().splitlines()[:3]
        result["probe"] = probe
    return result


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dest", type=Path, default=None,
                    help="backup destination dir (default <root>/backups)")
    ap.add_argument("--restore-drill", type=Path, default=None,
                    metavar="BACKUP_DIR",
                    help="restore BACKUP_DIR into a temp root, run search probe")
    ap.add_argument("--restore", type=Path, default=None,
                    metavar="BACKUP_DIR",
                    help="restore BACKUP_DIR into the LIVE root "
                         "(pre-restore snapshot first; asks unless --yes)")
    ap.add_argument("--yes", action="store_true",
                    help="skip the live-restore confirmation")
    ap.add_argument("--include-degraded", action="store_true",
                    help="allow restoring a DEGRADED backup (one whose "
                         "db was skipped at backup time) — explicit "
                         "override of the refusal")
    ap.add_argument("--full", action="store_true",
                    help="backup the whole root (default: research.db + Wiki)")
    ap.add_argument("--list", action="store_true",
                    help="list existing backups")
    args = ap.parse_args(argv)

    if args.list:
        backups = memory_root() / "backups"
        if backups.is_dir():
            for e in sorted(backups.iterdir()):
                if e.is_dir():
                    tag = ("  DEGRADED" if (e / ".degraded").is_file()
                           else "")
                    print(e.name + tag)
        return 0
    if args.restore_drill:
        result = restore_drill(args.restore_drill)
        print(json.dumps(result, ensure_ascii=False, indent=1))
        probe = result["probe"] or {}
        probe_ok = (not probe.get("exists") or probe.get("skipped")
                    or probe.get("returncode") == 0)
        findings_ok = (result.get("findings") or {}).get("ok", True)
        return 0 if (result["integrity_ok"] and probe_ok
                     and findings_ok) else 1
    if args.restore:
        if not args.yes:
            # non-interactive callers get a clean refusal, not EOFError
            if not sys.stdin.isatty():
                print("refused: not a tty — pass --yes to confirm "
                      "the live restore")
                return 2
            print(f"RESTORE {args.restore} -> {memory_root()} "
                  f"(pre-restore snapshot first). Type yes to proceed.")
            if input().strip().lower() not in ("yes", "y"):
                print("aborted")
                return 2
        try:
            result = restore(args.restore,
                             include_degraded=args.include_degraded)
        except RuntimeError as e:
            print(f"refused: {e}", file=sys.stderr)
            return 3
        print(json.dumps(result, ensure_ascii=False, indent=1))
        return 0 if (result["verify"] or {}).get("ok", False) else 1
    result = backup(args.dest, full=args.full)
    print(json.dumps(result, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
